/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LotIdRouteImport } from './routes/lot.$id'
import { Route as DashboardRegistrarRouteImport } from './routes/dashboard.registrar'
import { Route as CompradorLoteIdRouteImport } from './routes/comprador.$loteId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotIdRoute = LotIdRouteImport.update({
  id: '/lot/$id',
  path: '/lot/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRegistrarRoute = DashboardRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => DashboardRoute,
} as any)
const CompradorLoteIdRoute = CompradorLoteIdRouteImport.update({
  id: '/comprador/$loteId',
  path: '/comprador/$loteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/comprador/$loteId': typeof CompradorLoteIdRoute
  '/dashboard/registrar': typeof DashboardRegistrarRoute
  '/lot/$id': typeof LotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/comprador/$loteId': typeof CompradorLoteIdRoute
  '/dashboard/registrar': typeof DashboardRegistrarRoute
  '/lot/$id': typeof LotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/comprador/$loteId': typeof CompradorLoteIdRoute
  '/dashboard/registrar': typeof DashboardRegistrarRoute
  '/lot/$id': typeof LotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/comprador/$loteId'
    | '/dashboard/registrar'
    | '/lot/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/comprador/$loteId'
    | '/dashboard/registrar'
    | '/lot/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/comprador/$loteId'
    | '/dashboard/registrar'
    | '/lot/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  CompradorLoteIdRoute: typeof CompradorLoteIdRoute
  LotIdRoute: typeof LotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lot/$id': {
      id: '/lot/$id'
      path: '/lot/$id'
      fullPath: '/lot/$id'
      preLoaderRoute: typeof LotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/registrar': {
      id: '/dashboard/registrar'
      path: '/registrar'
      fullPath: '/dashboard/registrar'
      preLoaderRoute: typeof DashboardRegistrarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/comprador/$loteId': {
      id: '/comprador/$loteId'
      path: '/comprador/$loteId'
      fullPath: '/comprador/$loteId'
      preLoaderRoute: typeof CompradorLoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardRegistrarRoute: typeof DashboardRegistrarRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRegistrarRoute: DashboardRegistrarRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  CompradorLoteIdRoute: CompradorLoteIdRoute,
  LotIdRoute: LotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
